debug:disable_logs = false

$terminal = alacritty
$file_manager = nautilus
$menu = tofi-drun
# $menu = nc -U /run/user/1000/walker/walker.sock
$lock = loginctl lock-session

source = ~/.config/hypr/conf.d/hyprspace.conf
source = ~/.config/hypr/conf.d/hy3.conf

source = ~/.config/hypr/conf.d/env.conf
source = ~/.config/hypr/conf.d/exec.conf
source = ~/.config/hypr/conf.d/inputs.conf
source = ~/.config/hypr/conf.d/keybinds.conf
source = ~/.config/hypr/conf.d/looks.conf
source = ~/.config/hypr/conf.d/monitors.conf
source = ~/.config/hypr/conf.d/windowrules.conf

