general {
  hide_cursor = true
  ignore_empty_input = true
  immediate_render = true
}

background {
    monitor =
    path = screenshot
    blur_passes = 1
    blur_size = 12
}

label {
    monitor =
    text = $FAIL
    color = rgba(250, 100, 100, 0.5)
    font_size = 16
    font_family = Noto Sans

    position = 0, 20
    halign = center
    valign = bottom
}

label {
    monitor =
    text = $FPRINTPROMPT
    color = rgba(100, 100, 100, 0.5)
    font_size = 16
    font_family = Noto Sans

    position = 0, 60
    halign = center
    valign = bottom
}

label {
    monitor =
    text = Hi $USER, it's $TIME
    color = rgba(200, 200, 200, 1.0)
    font_size = 25
    font_family = Noto Sans

    position = 0, 120
    halign = center
    valign = center
}

auth {
  fingerprint {
    enabled = true
  }
}
