general {
    lock_cmd = pidof hyprlock || hyprlock
    # on_lock_cmd = secret-tool lock
    # on_unlock_cmd = notify-send test
    # before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on
}

listener {
    timeout = 80
    on-timeout = brightnessctl -s set 1
    on-resume = brightnessctl -r
}
listener {
    timeout = 120
    on-timeout = loginctl lock-session
}
listener {
    timeout = 300
    on-timeout = systemctl suspend
}
