plugin {
  hy3 {
    autotile {
      enabled = true
      trigger_width = 855
      trigger_height = 500
    }
    no_gaps_when_only = 1
    node_collapse_policy = 2
    tab_first_window = false
		tabs {
			height = 1
			from_top = true
			render_text = false
		}
  }
}
