# plugin {
#     overview {
#         autoDrag = true
#         autoScroll = true
#         showEmptyWorkspace = false
#         reverseSwipe = true
#         switchOnDrop = true
#     }
# }
#
# bind = SUPER, grave, overview:open
