# https://wiki.hyprland.org/Configuring/Variables/#input
input {
    kb_layout = us

    repeat_rate = 40
    repeat_delay = 400


    # -1.0 - 1.0, 0 means no modification.
    sensitivity = .5
    accel_profile = adaptive

    scroll_factor = 1
    natural_scroll = false

    follow_mouse = 1

    # floating windows in the special workspace will not block focusing windows in the regular workspace.
    special_fallthrough = false
    touchpad {
        natural_scroll = true
        scroll_factor = 0.3
        drag_lock = true
        disable_while_typing = true
    }
}
#
# Example per-device config
# See https://wiki.hyprland.org/Configuring/Keywords/#per-device-input-configs for more
device {
    name = apple-inc.-magic-trackpad-2
    sensitivity = 0.55
}
device {
    name = mx-anywhere-2-mouse
    sensitivity = 2
    accel_profile = adaptive
}
