# See https://wiki.hyprland.org/Configuring/Monitors/

# trigger when the switch is turning on/off
# bindl=,switch:on:Lid Switch,exec,hyprctl keyword monitor "eDP-1, disable"
# bindl=,switch:off:Lid Switch,exec,hyprctl keyword monitor "eDP-1, preferred, auto, 1"

#monitor=,preferred,0x0,1,mirror,eDP-1

monitor = eDP-1, preferred, auto, 1.5, bitdepth, 10
monitor = desc:Samsung Electric Company S34J55x HTOM600498, 3440x1440@75, 0x0, 1
monitor = , preferred, 0x0, 1
