monitorv2 {
  output = eDP-1
  mode = preferred
  scale = 1.5
  position = 0x0
  bitdepth = 10
}

monitorv2 {
  output = desc:Samsung Electric Company S34J55x HTOM600498
  mode = 3440x1440@75
  position = -3440x0
  scale = 1
}

# PyAnnote
monitorv2 {
  output = desc:Dell Inc. DELL S3425DW J6MPR44
  mode = 3440x1440@120
  position = -760.5x-1440
  scale = 1
}

monitor = , preferred, 0x0, 1
